postgrest:
    image: begriffs/postgrest
    container_name: postgrest
    ports:
        - "3000:3000"
    environment:
        POSTGRES_ANONYMOUS:       valhalla
        PG_ENV_POSTGRES_USER:     valhalla
        PG_ENV_POSTGRES_PASSWORD: valhalla
        PG_ENV_POSTGRES_DB:       valhalla
        POSTGRES_DB_NAME:         valhalla
        PG_PORT_5432_TCP_ADDR:    postgres
        PG_PORT_5432_TCP_PORT:    5432
        SCHEMA: public
        JWT_SECRET: secret
        POOL_SIZE: 10
    links:
        - "postgres:postgres"
postgres:
  container_name: postgres-9.5
  image: postgres-9.5
  ports:
    - "5555:5432"
  volumes_from:
    - "postgres-9.5-data"
